# Generated by Django 4.1.5 on 2023-01-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('users', models.ManyToManyField(to='meals.user')),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('threat_level', models.CharField(choices=[('Major', 'Major Threat'), ('Caution', 'Caution only'), ('NA', 'Not Assesed')], default='NA', max_length=255)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.usergroup')),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('major_allergen', models.BooleanField(default=False)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.usergroup')),
            ],
            options={
                'db_table': 'allergen',
            },
        ),
    ]
