# Generated by Django 4.1.5 on 2023-01-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grouprecipe',
            table='group_recipe',
        ),
        migrations.AlterModelTable(
            name='groupuser',
            table='group_user',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
        migrations.AlterModelTable(
            name='recipeingredient',
            table='recipe_ingredient',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='user_group',
        ),
        migrations.AlterModelTable(
            name='usergroupingredient',
            table='user_group_ingredient',
        ),
    ]
