# Generated by Django 4.1.5 on 2023-02-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AddField(
            model_name='food',
            name='allergens',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='meals.allergen'),
        ),
    ]
