# Generated by Django 4.1.5 on 2023-02-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_food_threat_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='allergens',
            field=models.ManyToManyField(null=True, to='meals.allergen'),
        ),
    ]
