# Generated by Django 4.1.5 on 2023-02-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_food_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, to='meals.allergen'),
        ),
    ]
