# Generated by Django 4.1.6 on 2023-02-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_food_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='meals.allergen'),
        ),
    ]
